export enum Configuration {
  APP_PORT = 'APP_PORT',
  APP_SECRET_KEY = 'APP_SECRET_KEY',
  TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_PORT = 'TYPEORM_PORT',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  APP_HTTP_PROTOCOL = 'APP_HTTP_PROTOCOL',
  APP_HOST = 'APP_HOST'
}
